;====================================================================
; Main.asm file generated by New Project wizard
;
; Created:   Çar May 22 2019
; Processor: PIC12F1840
; Compiler:  MPASM (MPLAB)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

#include p12f1840.inc                ; Include register definition file
#include DELAY.inc
#include SHIFTREG.inc
;====================================================================
; VARIABLES
;====================================================================
;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
RST   code  0x0 
      goto  Start


INTERRUP code 0x04
goto $


;initialized data
idata 0x20
delay_x db d'0'
delay_y db d'0'

lcd_temp db d'0'
bit_index db 0x0 
load_data db 0x0


;====================================================================
; CODE SEGMENT
;====================================================================

PGM   code 0x100
Start:

;4mhz
banksel OSCCON
bsf OSCCON, IRCF3
bsf OSCCON, IRCF2
bcf OSCCON, IRCF1
bsf OSCCON, IRCF0

bsf OSCCON, SCS1
bcf OSCCON, SCS0

DelayMs 100

banksel ANSELA
clrf ANSELA
banksel TRISA
bcf PORTA, DATA_PIN
bcf PORTA, CLOCK
bcf PORTA, STORE



      ; Write your code here
Loop:
banksel PORTA
bsf PORTA, RA0
DelayMs 250
DelayMs 250
banksel PORTA
bcf PORTA, RA0
DelayMs 250
DelayMs 250
Load_Shift_Var lcd_temp
incf lcd_temp

      goto  Loop

;====================================================================
      END
