
/* Main.c file generated by New Project wizard
 *
 * Created:   Cum Oca 23 2015
 * Processor: PIC16F877A
 * Compiler:  HI-TECH C for PIC10/12/16
 */

#include <htc.h>
#include "c:\\tc\\delay.c"
#define BAUD 9600 //Osilatore hesaba göre secilir
#define FOSC 4000000L //osc
#define DIVIDER ((int)(FOSC/(16UL * BAUD) -1))//SPBRG calculator
unsigned char seri_porttan_veri_al()
{
while(!RCIF);
return RCREG;

}
void seri_porta_veri_gonder(unsigned char jk)
 { while(!TXIF);
	 TXREG=jk;

	
	 }
void seri_portu_ayarla()
{SPBRG=DIVIDER;
	BRGH=1;
	SPEN=1;
	SYNC=0;
	TX9=0;
	TXEN=1;
	RX9=0;
	CREN=1;
	RC6=1;
	RC7=1;
}




int index=0;
char gelen_veri[8];char uyan[]="01010101";
int bolum=0;
void uyandir()
{
	for(int a=0;a<8;a++)
	{RB0=uyan[a]-48;
		DelayUs(1500);
		
	}
	
RB0=0;
	DelayUs(1500);
	
	
	
	}
	char senk[]="00000000";
	char senk1[]="11111111";
	void senkron()
{
	for(int a=0;a<8;a++)
	{RB0=senk[a]-48;
		DelayUs(1500);
		
	}
	for(int a=0;a<8;a++)
	{RB0=senk1[a]-48;
		DelayUs(1500);
		
	}
	RB0=0;
	DelayUs(1500);
	
	
	
	}
	
	
	
	
kodla_gonder(int sayi)

{index=0;
	while(index!=8)
 {
     gelen_veri[7-index]=sayi%2;
    bolum=sayi/2;
    sayi=bolum;
     index++;
 }
RB0=1;
DelayUs(2000-1); 
 RB0=0;
 DelayUs(1200-1);
 
 for(int a=0;a<8;a++)
 {
	 RB0=gelen_veri[a];
	 DelayUs(1500);
	
 }
 DelayUs(1000);
 RB0=0;
	
	
	
}





void main(void)
 {
	 
	 TRISB=0b11100000;
	 PORTB=0;
	 TRISC=0b10000000;
	 PORTC=0;
	 seri_portu_ayarla();
	 unsigned char gelen;
   // Write your code here
   while (1)
    
   {
if(RCIF==1)
gelen=RCREG;
	   if(gelen=='2')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('2');
	
		   
		   
	   }

 if(gelen=='4')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('4');
	
		   
		   
	   }
 if(gelen=='5')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('5');
	
		   
		   
	   }

 if(gelen=='7')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('7');
	
		   
		   
	   }
 if(gelen=='b')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('b');
	
		   
		   
	   }

 if(gelen=='d')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('d');
	
		   
		   
	   }

 if(gelen=='e')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('e');
	
		   
		   
	   }

 if(gelen=='g')
	   {
		   	uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('g');
	
		   
		   
	   }


	if(RB7==1)
	{

		uyandir();
		uyandir();
uyandir();
senkron();
		
		kodla_gonder('2');
		DelayMs(650);
	}		
	 if(RB6==1)
	{
uyandir();
		
		uyandir();
uyandir();
	senkron();
		kodla_gonder('b');
		DelayMs(650);
	}		  
/*	 if(RB5==1)
	{
uyandir();
		
	//	uyandir();
	//	senkron();
		kodla_gonder(55);
		DelayMs(650);
	}		     
	
*/	
	
	   
   }
   
   
   
 }