/* Main.c file generated by New Project wizard
 *
 * Created:   Cum Oca 15 2016
 * Processor: PIC18F4520
 * Compiler:  HI-TECH C for PIC18
 */


#include <htc.h>

#define false 0
#define true 1



char servo_number;
char dogru = false;



unsigned char seri_porttan_veri_al()
{
while( !RCIF );
return RCREG;
}
void seri_porta_veri_gonder(unsigned char jk)
 { while( !TXIF );
	 TXREG=jk;

	
	 }
void seri_portu_ayarla()
{SPBRG=25;
	BRGH=1;
	
	SPEN=1;
	
	SYNC=0;
	
	TX9=0;
	
	TXEN=1;
	
	RX9=0;
	
	CREN=1;
	
	
	/*
	RC6=1;
	
	RC7=1;
*/
	}

 volatile int temp;
volatile int temp2 = 0;
volatile int temp3 = 0;
void ADC_hazirla( )
{
	
	ADON	= 1; //ADC module is on...
	
	//Ref volt vdd-vss
	VCFG1 = 0;
	VCFG0 = 0;
	//0 daN AN3 analog channel gerisi digital output...
/*	PCFG3 = 1;
	PCFG2 = 0;
	PCFG1 = 1;
	PCFG0 = 1;
*/
	ADCON1 = 0b000000110;
	ADFM = 1; //Right Adjested...
	ADCS2 = 1;
	ADCS1 = 0;
	ADCS0 =0 ;

	ACQT2 = 1;
	ACQT1 = 0;
	ACQT0 = 0;
	
	}
int analogRead( char pin )
{
	if( pin == 0)
	{
	CHS3 = 0;
		CHS2 = 0;
		CHS1 = 0;
		CHS0 = 0;
	
	}
else if( pin == 1)
	{
	CHS3 = 0;
		CHS2 = 0;
		CHS1 = 0;
		CHS0 = 1;
	
	}
else if( pin == 2)
	{
	CHS3 = 0;
		CHS2 = 0;
		CHS1 = 1;
		CHS0 = 1;
	
	}


	//Pin seçildi...
	_delay( 10000 );
GO_DONE = 1;
	while( GO_DONE );
		ADIF = 0;
	return ADRES;
	}



struct _servo 
{
	
	
unsigned int angle ;
	
}
bir , iki , uc;



void interrupt FNC( )
{
	
	if( CCP1IF )
	{GIE = 0;
	//Interruptlar? kapat	
	if( servo_number == 0 )
	{
		
	if( dogru ) 
	{
		dogru = false;
	
		PORTBbits.RB4 = 0;
		TMR1 = 0;
		CCPR1 = 20000;
		servo_number = 1;
		
		
		}
	else
	{
		PORTBbits.RB4 = 1;
		TMR1 = 0;
		CCPR1 = 540 + 20 * bir.angle;
		dogru = true;
	
	
		
		}
		
		
	
	}	
	else if ( servo_number == 1 )
	{
	if( dogru ) 
	{
		dogru = false;
	PORTBbits.RB1 = 0;
		TMR1 = 0;
		CCPR1 = 20000;
		servo_number = 2;
		}
	else
	{
		dogru = true;
	PORTBbits.RB1 = 1;
		TMR1 = 0;
		CCPR1 = 540 + 20 * iki.angle ;
		
		}
		
		
		
		
		
	}
else
{

if( dogru ) 
	{
	PORTBbits.RB3 = 0;
		TMR1 = 0 ;
		CCPR1 = 20000;
		
		dogru = false;
	servo_number = 0;
		}
	else
	{
		PORTBbits.RB3 = 1;
		TMR1 = 0;
		CCPR1 = 540 + uc.angle*20 ;
		
		
		dogru = true;
	}
		
		

}	
		
		
		
		
CCP1IF = 0;		
	//Interruptlar? aç...

GIE=1;	
}
	
	
}

int sol= 0 , sag = 0 ;
void main(void)
 {
   // Write your code here
 TRISA = 0b00000111;
	TRISB = 0;
TRISB7 = 1;
	 PORTB = 0;
	 //RB0 1.servo
	 //RB1 2.servo
	 //RB2 3.Servo...
 ADC_hazirla();
	 _delay( 50000 );
	 seri_portu_ayarla();
	 _delay( 90000 );
	  _delay( 90000 );
	 GIE = 1;
	 PEIE = 1;
//Compare mode no change on CCP1 pin ...
	 CCP1M3 = 1;
	 CCP1M2 = 0;
	 CCP1M1 = 1;
	 CCP1M0 = 0;	 
	 CCP1IE = 1; //Interrupt enabled...
	 
	 //CCPR1 our register....
	 
	 T1RUN = 0;
	 
	 T1OSCEN = 0; //Timer 1 Oscillator disabled...
	 TMR1CS = 0; //Clock source internal fosc/4
	 //Timer1 Presc 1/1
	 T1CKPS1 = 0;
	 T1CKPS0 = 0;
	 
	 TMR1ON = 1 ;//Turn on the timer;
	 
	 
#define false 0
#define true 1
	 
unsigned int angle  = 3;
char open = false;
seri_porta_veri_gonder( 'S' );
seri_porta_veri_gonder( 'a' );
bir.angle = 3;
iki.angle = 3;
uc.angle = 3;
	 while (1)
	 {
		 temp = analogRead( 0 );
		 temp2 = analogRead( 1 );
		 temp3 = analogRead( 2 );
	
		 /*	
		seri_porta_veri_gonder( temp >> 8 );
		 _delay( 6000 );
		 seri_porta_veri_gonder(  temp );
		 _delay( 50000 );
		*/
		 //Birinci Servo için ....
		 if( temp < 30 )
		{
			bir.angle = bir.angle - 2;;
			if( bir.angle  < 3  ) bir.angle = 3;
				_delay( 15000 );
		}
		else if( temp > 800 )
		{
			bir.angle +=2;
		if( bir.angle > 190 )  bir.angle = 190;
						_delay( 15000 );
		}
		seri_porta_veri_gonder( temp3 );
		//ikinci servo...
	
		if( temp3 < 10 )
		{
			
			if( open ){ 
				open = false;
				uc.angle = 150  ;
				PORTBbits.RB5 = 1;
				}
			else
			{PORTBbits.RB5 = 0;
				open = true;
			uc.angle = 3 ;
				}
				
				while ( analogRead( 2 )   < 15 );
		}
	

		if( temp2 < 30 )
		{
			iki.angle = iki.angle - 2;
			if( iki.angle  < 3 ) iki.angle = 3;
				
		_delay( 15000 );
			}
	else	if( temp2 > 800 )
		{
			iki.angle = iki.angle + 2;
		if( iki.angle > 190 )  iki.angle = 190;
						
		
		_delay( 15000 );
		
		}
		}
	 
      ;
 }
